import { Annapurna_SIL } from 'next/font/google';
import { PiCowboyHat } from 'react-icons/pi';
import { FaCheckCircle } from 'react-icons/fa';
import { RiTimeFill } from 'react-icons/ri';
import { AiOutlineFieldTime } from 'react-icons/ai';
import { MdPeopleAlt } from 'react-icons/md';
import { HiMiniArrowSmallUp } from 'react-icons/hi2';
import { HiMiniArrowSmallDown } from 'react-icons/hi2';
import { IoIosPeople } from 'react-icons/io';
import { MdPersonAddAlt1 } from 'react-icons/md';
import { GrUserFemale } from 'react-icons/gr';
import { GrUserManager } from 'react-icons/gr';

export const PAYMENTS_DATA = [
  {
    EmployeeID: 'EMP001',
    email: 'alice@gmail.com',
    Name: 'Alice Johnson',
    Position: 'Software Dev',
    Department: 'Engineering',
    Status: 'Full-Time',
    BaseSalary: 320000,
    Allowances: 40000, // Travel, Medical, Housing
    Deductions: 24000, // Taxes, Insurance.
    OvertimeHours: 10,
    OvertimeRate: 1600, // 10 * 1600 (OvertimeHours * OvertimeRate)
    BankAccountNo: '1234567890',
  },
  {
    EmployeeID: 'EMP002',
    email: 'bob@gmail.com',
    Name: 'Bob Smith',
    Position: 'HR Manager',
    Department: 'Human Resources',
    Status: 'Full-Time',
    BaseSalary: 400000,
    Allowances: 56000,
    Deductions: 32000,
    OvertimeHours: 5,
    OvertimeRate: 2000,
    BankAccountNo: '0987654321',
  },
  {
    EmployeeID: 'EMP003',
    email: 'clara@gmail.com',
    Name: 'Clara Lee',
    Position: 'Accountant',
    Department: 'Finance',
    Status: 'Part-Time',
    BaseSalary: 280000,
    Allowances: 24000,
    Deductions: 16000,
    OvertimeHours: 8,
    OvertimeRate: 1200,
    BankAccountNo: '5678901234',
  },
  {
    EmployeeID: 'EMP004',
    email: 'david@gmail.com',
    Name: 'David Wilson',
    Position: 'IT Technician',
    Department: 'IT Support',
    Status: 'Full-Time',
    BaseSalary: 304000,
    Allowances: 32000,
    Deductions: 20000,
    OvertimeHours: 12,
    OvertimeRate: 1440,
    BankAccountNo: '6789012345',
  },
  {
    EmployeeID: 'EMP005',
    email: 'emily@gmail.com',
    Name: 'Emily Brown',
    Position: 'Sales Manager',
    Department: 'Product Management',
    Status: 'Full-Time',
    BaseSalary: 360000,
    Allowances: 48000,
    Deductions: 28000,
    OvertimeHours: 7,
    OvertimeRate: 1760,
    BankAccountNo: '8901234567',
  },
  {
    EmployeeID: 'EMP006',
    email: 'frank@gmail.com',
    Name: 'Frank White',
    Position: 'Marketing Lead',
    Department: 'Marketing',
    Status: 'Freelancer',
    BaseSalary: 336000,
    Allowances: 44000,
    Deductions: 24000,
    OvertimeHours: 6,
    OvertimeRate: 1600,
    BankAccountNo: '2345678901',
  },
  {
    EmployeeID: 'EMP007',
    email: 'grace@gmail.com',
    Name: 'Grace Hall',
    Position: 'Data Analyst',
    Department: 'Data Science',
    Status: 'Part-Time',
    BaseSalary: 312000,
    Allowances: 36000,
    Deductions: 20000,
    OvertimeHours: 9,
    OvertimeRate: 1360,
    BankAccountNo: '3456789012',
  },
  {
    EmployeeID: 'EMP008',
    email: 'henry@gmail.com',
    Name: 'Henry Adams',
    Position: 'Operations Manager',
    Department: 'Operations',
    Status: 'Full-Time',
    BaseSalary: 376000,
    Allowances: 48000,
    Deductions: 32000,
    OvertimeHours: 4,
    OvertimeRate: 2000,
    BankAccountNo: '4567890123',
  },
  {
    EmployeeID: 'EMP009',
    email: 'ivy@gmail.com',
    Name: 'Ivy Carter',
    Position: 'UX Designer',
    Department: 'Design',
    Status: 'Freelancer',
    BaseSalary: 328000,
    Allowances: 40000,
    Deductions: 25600,
    OvertimeHours: 8,
    OvertimeRate: 1520,
    BankAccountNo: '5678901234',
  },
  {
    EmployeeID: 'EMP010',
    email: 'jack@gmail.com',
    Name: 'Jack Taylor',
    Position: 'Project Manager',
    Department: 'Product Management',
    Status: 'Full-Time',
    BaseSalary: 400000,
    Allowances: 64000,
    Deductions: 40000,
    OvertimeHours: 3,
    OvertimeRate: 2400,
    BankAccountNo: '6789012345',
  },
];

export const ATTENDANCE_DATA = [
  {
    icon: <FaCheckCircle size={13} />,
    label: 'Total Employees Present',
    count: 120,
    arrow: <HiMiniArrowSmallUp />,
    per: '5%',
    tag: 'from Yesterday',
  },
  {
    icon: <AiOutlineFieldTime size={15} />,
    label: 'Late Arrivals Today',
    count: 15,
    arrow: <HiMiniArrowSmallUp size={15} />,
    per: '3 people',
    tag: 'compared to last week',
  },
  {
    icon: <MdPeopleAlt size={15} />,
    label: 'Employees Absent',
    key: 'leaves',
    count: 8,
    arrow: <HiMiniArrowSmallDown size={15} />,
    per: '2 people',
    tag: 'comapred to last monday',
    styles: 'bg-red-100 text-red-700',
  },
  {
    icon: <RiTimeFill size={15} />,
    label: 'Average Check-In Time ',
    count: '08:25 AM',
    tag: 'cosistent with last week',
    styles: 'self-start',
  },
];

export const EMP_DATA = [
  {
    icon: <IoIosPeople size={24} />,
    label: 'Total Employee',
    key: 'totalEmployees',
    count: 0,
    iconstyles: '',
  },
  {
    icon: <MdPersonAddAlt1 size={24} />,
    label: 'New Employee',
    key: 'noFundAccount',
    count: 0,
    iconstyles: 'bg-green-400',
  },
  {
    icon: <GrUserFemale size={24} />,
    label: 'Female',
    key: 'femaleEmployees',
    count: 0,
    iconstyles: 'bg-blue-400',
  },
  {
    icon: <GrUserManager size={24} />,
    label: 'Male',
    key: 'maleEmployees',
    count: 0,
    iconstyles: 'bg-purple-400',
  },
];

export const SALARY_COMPONENTS = [
  {
    label: 'Basic Salary',
    type: 'text',
    bodyKey: 'basic',
    hint: 'in %',
  },
  {
    label: 'Dearness Allowance(DA)',
    type: 'text',
    bodyKey: 'da',
    hint: 'in %',
  },
  {
    label: 'House Rent Allowance(HRA)',
    type: 'text',
    bodyKey: 'hra',
    hint: 'in %',
  },
  {
    label: 'Other Allowances',
    type: 'text',
    bodyKey: 'otherAllowances',
    hint: 'in %',
  },
  {
    label: 'Provident Fund(PF)',
    type: 'text',
    bodyKey: 'pf',
    hint: 'in %',
  },
];
